apiVersion: batch/v1
kind: CronJob
metadata:
  name: pipeline-trigger
  namespace: bruindigest
spec:
  schedule: "0 8,14,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pipeline-trigger
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST http://backend-service:3001/api/articles/generate \
                -H "Content-Type: application/json" \
                -d '{"auto_trigger": true}'
          restartPolicy: OnFailure 